name: Repository Creation Trigger

on:
  repository_dispatch:
    types: [repository_created]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Print repository details
      run: "echo 'Repository created: ${{ github.repository }}'"