name: Repository Creation Trigger

on:
  create:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Print repository details
      run: "echo 'Repository created: ${{ github.repository }}'"